spring:
  application:
    name: poc-2-sqs-fifo-consumer-ms-springboot
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        profile:
          name: default
server:
  port: 8082